version: '3.8'

services:
  backend:
    build: .
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
    env_file:
      - .env
    volumes:
      - ./.env:/app/.env
    networks:
      - band-network
    expose:
      - "8080"

# Using MongoDB Atlas instead of local MongoDB instance
# MongoDB Atlas connection details should be configured in .env file

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=development
    expose:
      - "3000"
    networks:
      - band-network

networks:
  band-network:
