package models

import (
	"database/sql"
	"fmt"
	"math/rand"
	"time"
)

type VerificationCode struct {
	ID          int       `json:"id"`
	PhoneNumber string    `json:"phone_number"`
	Code        string    `json:"code"`
	ExpiresAt   time.Time `json:"expires_at"`
	CreatedAt   time.Time `json:"created_at"`
}

func CreateVerificationTable(db *sql.DB) error {
	_, err := db.Exec(`
		CREATE TABLE IF NOT EXISTS verification_codes (
			id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
			phone_number VARCHAR(20) NOT NULL,
			code VARCHAR(6) NOT NULL,
			expires_at TIMESTAMP NOT NULL,
			created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
		)
	`)
	return err
}

func GenerateVerificationCode(phoneNumber string) string {
	rand.New(rand.NewSource(time.Now().UnixNano()))
	code := fmt.Sprintf("%06d", rand.Intn(999999))
	return code
}
